version: '3'
services:
  postgres:
    container_name: test_postgres
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - etop_postgres_data:/var/lib/postgresql/data
      - ~/work/src/backend/db:/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      - POSTGRES_DATA=/var/lib/postgresql/data/pgdata
